export const faqStructure = [
  {
    sectionName: 'faq.questionsAboutFlexpool',
    contents: [
      'questions-about-flexpool/how-to-join.md',
      'questions-about-flexpool/flexpool-pool-fee.md',
      'questions-about-flexpool/what-is-minimum-payout.md',
      'questions-about-flexpool/when-do-payouts-happen.md',
      'questions-about-flexpool/how-long-will-i-receive-payout.md',
      'questions-about-flexpool/what-is-payout-criteria.md',
      'questions-about-flexpool/balance-is-zero.md',
      'questions-about-flexpool/what-reward-scheme.md',
      'questions-about-flexpool/does-flexpool-have-transaction-fees.md',
      'questions-about-flexpool/does-flexpool-send-weekly-payouts-regardless-of-balance.md',
      'questions-about-flexpool/should-i-use-ssl.md',
      'questions-about-flexpool/how-can-i-transfer-unpaid-balance-to-another-account.md',
      'questions-about-flexpool/how-unstable-reported-hashrate-effect-my-payouts.md',
      'questions-about-flexpool/why-do-i-have-unstable-reported-hashrate.md',
      'questions-about-flexpool/how-share-count-calculated.md',
      'questions-about-flexpool/what-does-zil-mean.md',
      'questions-about-flexpool/what-happens-inactive-worker.md',
      'questions-about-flexpool/no-longer-mining.md',
    ],
  },
  {
    sectionName: 'faq.miningBasics',
    contents: [
      'mining-theory/what-is-hashrate.md',
      'mining-theory/what-is-a-share.md',
      'mining-theory/what-are-stale-shares.md',
      'mining-theory/what-is-a-block.md',
      'mining-theory/the-basics-of-mining-theory.md',
      'mining-theory/what-is-share-difficulty.md',
    ],
  },
];
